base:
  project: Consignment-Pricing-Using-MLops-DVC
  random_state: 180
  target_data: line_item_value

data_source: 
  local_data: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data_given/Consignment_pricing_raw.csv

load_data:
  raw_data_csv: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/raw/Consignment_pricing_raw.csv
data:
  processed: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/processed/Consignment_pricing_processed.csv

final_data:
  transformed_data: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/transformed_data/Consignment_pricing_transformed.csv

raw_data:
  raw: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/consignment_data/Consignment_pricing_raw.csv

columns:
  select: ["pq_#",'po_/_so_#', 'asn/dn_#','country', 'fulfill_via', 'vendor_inco_term',
       'sub_classification', 'unit_of_measure_(per_pack)',
       'line_item_quantity', 'line_item_value', 'pack_price', 'unit_price',
       'first_line_designation', 'freight_cost_(usd)', 'shipment_mode',
        'line_item_insurance_(usd)', 'days_to_process']

split_data:
  train_path: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/split_data/Consignment_pricing_train.csv
  test_path: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/split_data/Consignment_pricing_test.csv
  split_ratio: 0.20


model_dirs: saved_models

estimators: 
  RandomForestRegressor:
    params:
      criterion: mae
      max_deapth: 10
      min_sample_leaf: 2
      min_sample_split: 8
      n_estimators: 80
      oob_score: True

webapp_model_dir: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/prediction_service/model/model_rf.pkl

data1:
  training_data: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/main_data/train_data.csv
  test_data:  /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/main_data/test_data.csv
  processed: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/data/processed/Consignment_pricing_processed.csv

RandomizedSearchCV:
  n_iter: 3
  scoring: r2
  verbose: 5
  cv: 10
  n_jobs: -1
  return_train_score:  True
  params:
    n_estimators: [5,10,20,40,80]
    criterion: ['mse','mae']
    max_depth: [2,5,10]
    min_samples_split : [2,4,8,12]
    min_samples_leaf: [2,4,8,10]



reports:
  scores: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/reports/scores.json
  params: /home/dataguy/Desktop/Consignment-Pricing-Using-Mlops-DVC-main/reports/params.json

mlflow_config_dir:
  artifacts_dir: artifacts
  experiment_name: RandomForestRegression
  run_name: Consignment_Pricing_Mlops
  registered_model_name: RandomForestConsignmentModel
  remote_server_uri: http://127.0.0.1:1234